// Tracking Link CRUD. Mirrors conventions from
// worker/database/affiliate-partners.js and offers.js.
//
// Every affiliate destination goes through here -- no raw URLs
// embedded in templates or casino records beyond the legacy
// casinos.affiliate_url fallback, which this system supersedes but
// does not remove (see migrations/0025_tracking_links.sql).

const LINK_STATUSES = ['active', 'disabled', 'archived'];

function randomHex(length) {
  const arr = new Uint8Array(length);
  crypto.getRandomValues(arr);
  return Array.from(arr, b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * System-generated by default (brief requirement, §7): short,
 * URL-safe, collision-checked against both existing tracking_codes
 * AND existing casino slugs -- a tracking_code that happened to match
 * a casino slug would be resolvable but ambiguous with the legacy
 * fallback path (see worker/tracking/redirect.js's resolution order),
 * so it's blocked here rather than only documented as a risk.
 */
export async function generateTrackingCode(db) {
  for (let attempt = 0; attempt < 10; attempt++) {
    const candidate = `trk-${randomHex(5)}`; // trk- prefix keeps it visually distinct from casino slugs in logs/URLs
    if (!(await codeCollides(db, candidate))) return candidate;
  }
  throw new Error('Failed to generate a unique tracking code after 10 attempts');
}

async function codeCollides(db, code, excludeId = null) {
  const linkMatch = await db.prepare(
    `SELECT id FROM tracking_links WHERE tracking_code = ? ${excludeId ? 'AND id != ?' : ''} LIMIT 1`
  ).bind(...(excludeId ? [code, excludeId] : [code])).first();
  if (linkMatch) return true;

  const casinoMatch = await db.prepare(`SELECT id FROM casinos WHERE slug = ? LIMIT 1`).bind(code).first();
  return !!casinoMatch;
}

const RESERVED_CODES = new Set(['create', 'update', 'delete', 'list', 'get', 'admin', 'api']);

/**
 * Validates an admin-supplied CUSTOM tracking code (§7: allowed, but
 * must be unique, URL-safe, valid, not reserved, and not collide with
 * a casino slug). System-generated codes skip this since they're
 * already guaranteed safe by construction.
 */
export async function validateCustomTrackingCode(db, code, excludeId = null) {
  if (!/^[a-zA-Z0-9_-]{3,64}$/.test(code)) {
    throw new Error('Tracking code must be 3-64 characters: letters, numbers, hyphens, and underscores only');
  }
  if (RESERVED_CODES.has(code.toLowerCase())) {
    throw new Error(`"${code}" is a reserved word and cannot be used as a tracking code`);
  }
  if (await codeCollides(db, code, excludeId)) {
    throw new Error(`Tracking code "${code}" is already in use (either by another tracking link or a casino's URL slug)`);
  }
}

/**
 * Open-redirect guard (brief requirement): destination must be a
 * well-formed absolute https URL, and must not point back at this
 * site's own domain. Applied to destination_url and every GEO
 * override destination, at write time -- never at redirect time from
 * user input, since the redirect route only ever takes an opaque
 * tracking_code, not a URL.
 */
export function validateDestinationUrl(url, ownDomains = []) {
  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error(`"${url}" is not a valid URL`);
  }
  if (parsed.protocol !== 'https:') {
    throw new Error('Destination URL must use https://');
  }
  if (ownDomains.some(domain => parsed.hostname === domain || parsed.hostname.endsWith(`.${domain}`))) {
    throw new Error('Destination URL cannot point back at this site\'s own domain');
  }
}

function validateLinkFields(link) {
  if (link.status && !LINK_STATUSES.includes(link.status)) {
    throw new Error(`Invalid status: ${link.status}. Must be one of: ${LINK_STATUSES.join(', ')}`);
  }
  if (!link.internal_name) {
    throw new Error('internal_name is required');
  }
}

export async function getTrackingLinkById(db, id) {
  return await db.prepare(`SELECT * FROM tracking_links WHERE id = ? LIMIT 1`).bind(id).first();
}

export async function getTrackingLinkByCode(db, code) {
  return await db.prepare(`SELECT * FROM tracking_links WHERE tracking_code = ? LIMIT 1`).bind(code).first();
}

export async function getAllTrackingLinksAdmin(db, { casinoId = null, status = null, healthStatus = null, search = null, limit = 100, offset = 0 } = {}) {
  const conditions = [];
  const params = [];

  if (casinoId != null) { conditions.push('casino_id = ?'); params.push(casinoId); }
  if (status) { conditions.push('status = ?'); params.push(status); }
  if (healthStatus) { conditions.push('health_status = ?'); params.push(healthStatus); }
  if (search) { conditions.push('(internal_name LIKE ? OR tracking_code LIKE ?)'); params.push(`%${search}%`, `%${search}%`); }

  const whereClause = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
  params.push(limit, offset);

  const result = await db.prepare(`
    SELECT * FROM tracking_links
    ${whereClause}
    ORDER BY updated_at DESC
    LIMIT ? OFFSET ?
  `).bind(...params).all();

  return result.results || [];
}

export async function createTrackingLink(db, link, { ownDomains = [] } = {}) {
  validateLinkFields(link);
  validateDestinationUrl(link.destination_url, ownDomains);

  let trackingCode = link.tracking_code;
  if (trackingCode) {
    await validateCustomTrackingCode(db, trackingCode);
  } else {
    trackingCode = await generateTrackingCode(db);
  }

  const result = await db.prepare(`
    INSERT INTO tracking_links (
      internal_name, tracking_code, destination_url, casino_id, partner_id, program_id, offer_id,
      campaign, source, medium, content, allowed_geos, blocked_geos, priority, status,
      created_by, updated_by
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).bind(
    link.internal_name,
    trackingCode,
    link.destination_url,
    link.casino_id ?? null,
    link.partner_id ?? null,
    link.program_id ?? null,
    link.offer_id ?? null,
    link.campaign ?? null,
    link.source ?? null,
    link.medium ?? null,
    link.content ?? null,
    link.allowed_geos ? JSON.stringify(link.allowed_geos) : null,
    link.blocked_geos ? JSON.stringify(link.blocked_geos) : null,
    link.priority ?? 0,
    link.status || 'active',
    link.created_by ?? null,
    link.created_by ?? null
  ).run();

  return { id: result.meta.last_row_id, tracking_code: trackingCode };
}

export async function updateTrackingLink(db, id, updates, { ownDomains = [] } = {}) {
  const existing = await getTrackingLinkById(db, id);
  if (!existing) throw new Error('Tracking link not found');

  const merged = { ...existing, ...updates };
  validateLinkFields(merged);
  if (updates.destination_url) {
    validateDestinationUrl(updates.destination_url, ownDomains);
  }
  if (updates.tracking_code && updates.tracking_code !== existing.tracking_code) {
    await validateCustomTrackingCode(db, updates.tracking_code, id);
  }

  await db.prepare(`
    UPDATE tracking_links SET
      internal_name = ?, tracking_code = ?, destination_url = ?, casino_id = ?, partner_id = ?,
      program_id = ?, offer_id = ?, campaign = ?, source = ?, medium = ?, content = ?,
      allowed_geos = ?, blocked_geos = ?, priority = ?, status = ?, updated_by = ?, updated_at = CURRENT_TIMESTAMP
    WHERE id = ?
  `).bind(
    merged.internal_name,
    merged.tracking_code,
    merged.destination_url,
    merged.casino_id ?? null,
    merged.partner_id ?? null,
    merged.program_id ?? null,
    merged.offer_id ?? null,
    merged.campaign ?? null,
    merged.source ?? null,
    merged.medium ?? null,
    merged.content ?? null,
    merged.allowed_geos ? JSON.stringify(merged.allowed_geos) : null,
    merged.blocked_geos ? JSON.stringify(merged.blocked_geos) : null,
    merged.priority ?? 0,
    merged.status,
    updates.updated_by ?? existing.updated_by,
    id
  ).run();
}

export async function setLinkStatus(db, id, status, updatedBy = null) {
  if (!LINK_STATUSES.includes(status)) {
    throw new Error(`Invalid status: ${status}. Must be one of: ${LINK_STATUSES.join(', ')}`);
  }
  return await db.prepare(
    `UPDATE tracking_links SET status = ?, updated_by = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`
  ).bind(status, updatedBy, id).run();
}

// ── GEO destination overrides ──────────────────────

export async function getGeoDestinations(db, trackingLinkId) {
  const result = await db.prepare(
    `SELECT * FROM tracking_link_geo_destinations WHERE tracking_link_id = ? ORDER BY country_code ASC`
  ).bind(trackingLinkId).all();
  return result.results || [];
}

export async function setGeoDestinations(db, trackingLinkId, destinations, { ownDomains = [] } = {}) {
  for (const d of destinations || []) {
    validateDestinationUrl(d.destination_url, ownDomains);
  }

  await db.prepare(`DELETE FROM tracking_link_geo_destinations WHERE tracking_link_id = ?`).bind(trackingLinkId).run();

  for (const d of destinations || []) {
    await db.prepare(`
      INSERT INTO tracking_link_geo_destinations (tracking_link_id, country_code, destination_url)
      VALUES (?, ?, ?)
    `).bind(trackingLinkId, d.country_code.toUpperCase(), d.destination_url).run();
  }
}

/**
 * Dependent-record check. Tracking links are never hard-deleted via
 * the API (no DELETE endpoint planned, per migration 0022's header),
 * so this exists primarily so casino/offer deletion flows (System 1/2)
 * can give a clear message instead of a raw FK error -- mirrors
 * getPartnerDependents() / getCasinoOfferDependents().
 */
export async function getCasinoTrackingLinkDependents(db, casinoId) {
  const row = await db.prepare(`SELECT COUNT(*) AS c FROM tracking_links WHERE casino_id = ?`).bind(casinoId).first();
  return row.c > 0 ? { tracking_links: row.c } : null;
}

export async function getOfferTrackingLinkDependents(db, offerId) {
  const row = await db.prepare(`SELECT COUNT(*) AS c FROM tracking_links WHERE offer_id = ?`).bind(offerId).first();
  return row.c > 0 ? { tracking_links: row.c } : null;
}

export async function getPartnerTrackingLinkDependents(db, partnerId) {
  const row = await db.prepare(`SELECT COUNT(*) AS c FROM tracking_links WHERE partner_id = ?`).bind(partnerId).first();
  return row.c > 0 ? { tracking_links: row.c } : null;
}

export async function getProgramTrackingLinkDependents(db, programId) {
  const row = await db.prepare(`SELECT COUNT(*) AS c FROM tracking_links WHERE program_id = ?`).bind(programId).first();
  return row.c > 0 ? { tracking_links: row.c } : null;
}
