name: D1 Database Schema

on:
  workflow_dispatch:

jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Show Wrangler version
        run: wrangler --version

      - name: Print D1 Schemas
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd en

          wrangler d1 execute levelcasino-db --remote --command "PRAGMA table_info(casinos);"
          wrangler d1 execute levelcasino-db --remote --command "PRAGMA table_info(reviews);"
          wrangler d1 execute levelcasino-db --remote --command "PRAGMA table_info(news);"
          wrangler d1 execute levelcasino-db --remote --command "PRAGMA table_info(pages);"
          wrangler d1 execute levelcasino-db --remote --command "PRAGMA table_info(faqs);"
